version: "3.7"

services:
  api-prod:
    container_name: api-prod
    build:
      context: .
      target: prod
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      BACKEND_HOST: ${BACKEND_HOST}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}

  api-dev:
    container_name: api-dev
    build:
      context: .
      target: dev
    restart: always
    volumes:
      - ./src/:/app/
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}

