version: "3.7"

services:
  api-prod:
    container_name: api-prod
    tty: true
    build:
      context: .
      target: prod
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      BACKEND_HOST: ${BACKEND_HOST}
      # DATABASE_HOST: ${DATABASE_HOST}
      # DATABASE_PORT: ${DATABASE_PORT}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_USER: ${DATABASE_USER}
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # DATABASE_SSL: ${DATABASE_SSL}

  api-dev:
    container_name: api-dev
    tty: true
    build:
      context: .
      target: dev
    restart: always
    volumes:
      - ./src/:/app/
    ports:
      - 8000:8000
      - 9226:9226
    environment:
      PORT: ${PORT}
      BACKEND_HOST: ${BACKEND_HOST}
      # DATABASE_HOST: ${DATABASE_HOST}
      # DATABASE_PORT: ${DATABASE_PORT}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_USER: ${DATABASE_USER}
      # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # DATABASE_SSL: ${DATABASE_SSL}

